// Real Estate Alliance League, Illinois, USA
// ThisIsREAL.io    /    support@thisisreal.io
// Submit Fee Contract — Burns 1 REAL token per property, forum, or poll submission
//
// SPDX-License-Identifier: MIT
// Compatible with OpenZeppelin Contracts ^5.0.0
pragma solidity ^0.8.28;

import {ReentrancyGuard} from "@openzeppelin/contracts@5.2.0/utils/ReentrancyGuard.sol";

interface IERC20Burnable {
    function burnFrom(address account, uint256 amount) external;
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
}

contract SubmitFee is ReentrancyGuard {
    IERC20Burnable public constant REAL_TOKEN =
        IERC20Burnable(0x325Aa344761c19F7ab6dc45A95f01d6907A30DCA);

    uint256 public constant SUBMISSION_FEE = 1 * 10 ** 18; // 1 REAL (18 decimals)

    enum SubmissionType {
        Property,
        Forum,
        Poll
    }

    event Submitted(
        address indexed submitter,
        SubmissionType indexed submissionType,
        bytes32 indexed backendId,
        string title
    );

    /**
     * @dev Submit a property, forum thread, or poll.
     *      Burns 1 REAL from the caller's wallet.
     *      The caller must have previously approved this contract
     *      to spend at least 1 REAL on the REAL token contract.
     * @param submissionType The type of submission (0 = Property, 1 = Forum, 2 = Poll)
     * @param title The title of the submission
     * @param backendId A unique identifier generated by the backend
     */
    function submit(
        SubmissionType submissionType,
        string calldata title,
        bytes32 backendId
    ) external nonReentrant {
        require(bytes(title).length > 0, "SubmitFee: Title cannot be empty");
        require(backendId != bytes32(0), "SubmitFee: Backend ID cannot be zero");
        require(
            REAL_TOKEN.balanceOf(msg.sender) >= SUBMISSION_FEE,
            "SubmitFee: Insufficient REAL balance"
        );
        require(
            REAL_TOKEN.allowance(msg.sender, address(this)) >= SUBMISSION_FEE,
            "SubmitFee: Insufficient allowance, approve this contract on REAL token first"
        );

        REAL_TOKEN.burnFrom(msg.sender, SUBMISSION_FEE);

        emit Submitted(msg.sender, submissionType, backendId, title);
    }
}
